# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140617172649) do

  create_table "detallefacturas", force: true do |t|
    t.integer  "NroLinDet"
    t.string   "TipoCodigo"
    t.string   "VlrCodigo"
    t.integer  "IndExe"
    t.string   "IndAgente"
    t.integer  "MntBaseFaena"
    t.integer  "MntMargComer"
    t.integer  "PrcConsFinal"
    t.string   "NmbItem"
    t.string   "DscItem"
    t.float    "QtyRef"
    t.string   "UnmdRef"
    t.integer  "PrcRef"
    t.float    "QtyItem"
    t.float    "SubQty"
    t.date     "FchElabor"
    t.date     "FchVencim"
    t.string   "UnmdItem"
    t.float    "PrcItem"
    t.integer  "PrcOtrMon"
    t.string   "Moneda"
    t.float    "FctConv"
    t.float    "DctoOtrMnda"
    t.float    "RecargoOtrMnda"
    t.float    "MontoItemOtrMnda"
    t.float    "DescuentoPct"
    t.integer  "DescuentoMonto"
    t.string   "TipoDscto"
    t.float    "ValorDscto"
    t.float    "RecargoPct"
    t.integer  "RecargoMonto"
    t.string   "TipoRecargo"
    t.integer  "ValorRecargo"
    t.string   "CodImpAdic"
    t.integer  "MontoItem"
    t.integer  "factura_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "detallefacturas", ["factura_id"], name: "index_detallefacturas_on_factura_id"

  create_table "facturas", force: true do |t|
    t.string   "Version"
    t.integer  "TipoDte"
    t.integer  "Folio"
    t.date     "FchEmis"
    t.string   "TipoDespacho"
    t.integer  "IndServicio"
    t.integer  "MntBruto"
    t.integer  "FmaPago"
    t.date     "FchCancel"
    t.integer  "MntCancel"
    t.integer  "SaldoInsol"
    t.date     "FchPago"
    t.integer  "MntPago"
    t.string   "GlosaPagos"
    t.date     "PeriodoDesde"
    t.date     "PeriodoHasta"
    t.string   "MedioPago"
    t.string   "TipoCtaPAgo"
    t.string   "NumCtaPago"
    t.string   "BcoPago"
    t.string   "TermPagoCdg"
    t.string   "TermPAgoGlosa"
    t.integer  "TermPagoDias"
    t.date     "FchVenc"
    t.string   "RUTEmisor"
    t.string   "RznSoc"
    t.string   "GiroEmis"
    t.string   "Telefono"
    t.string   "CorreoEmisor"
    t.integer  "Acteco"
    t.string   "Sucursal"
    t.integer  "CdgSIISucur"
    t.string   "DirOrigen"
    t.string   "CmnaOrigen"
    t.string   "CiudadOrigen"
    t.string   "CdgVendedor"
    t.string   "RutMandante"
    t.string   "RUTReceptor"
    t.string   "CdgIntRecep"
    t.string   "RznSocRecep"
    t.string   "NumId"
    t.string   "Nacionalidad"
    t.string   "GiroRecep"
    t.string   "Contacto"
    t.string   "CorreoRecep"
    t.string   "DirRecep"
    t.string   "CmnaRecep"
    t.string   "CiudadRecep"
    t.string   "DirPostal"
    t.string   "CmnaPostal"
    t.string   "CiudadPostal"
    t.string   "RUTSolicita"
    t.string   "Patente"
    t.string   "RUTTRans"
    t.string   "RUTChofer"
    t.string   "NombreChofer"
    t.string   "DirDest"
    t.string   "CmnaDest"
    t.string   "CiudadDest"
    t.integer  "MntNeto"
    t.integer  "MntExe"
    t.integer  "MntBase"
    t.integer  "MntMargenCom"
    t.float    "TasaIVA"
    t.integer  "IVA"
    t.integer  "IVAProp"
    t.integer  "IVATerc"
    t.string   "TipoImp"
    t.integer  "TasaImp"
    t.integer  "MontoImp"
    t.integer  "CredEC"
    t.integer  "GmtDep"
    t.integer  "MntTotal"
    t.integer  "MontoNF"
    t.integer  "MontoPeriodo"
    t.integer  "SaldoAnterior"
    t.integer  "VlrPagar"
    t.string   "TpoMoneda"
    t.integer  "TpoCambio"
    t.float    "MntNetoOtrMnda"
    t.float    "MntExeOtrMnda"
    t.float    "MntFaeCarneOtrMnda"
    t.integer  "MntMargComOtrMnda"
    t.float    "IVAOtrMnda"
    t.string   "TipoImpOtrMnda"
    t.integer  "TasaImpOtrMnda"
    t.integer  "VlrImpOtrMnda"
    t.float    "MntTotOtrMnda"
    t.string   "NroSti"
    t.string   "integer"
    t.string   "GlosaSti"
    t.string   "text"
    t.string   "OrdenSti"
    t.string   "SubTotNetoSti"
    t.string   "float"
    t.string   "SubTotIVASti"
    t.string   "SubTotAdicSti"
    t.string   "SubTotExeSti"
    t.string   "ValSubTotSti"
    t.string   "LineasDeta"
    t.integer  "NroLinDr"
    t.string   "TpoMov"
    t.string   "GlosaDr"
    t.string   "TpoValor"
    t.float    "ValorDr"
    t.float    "ValorDrOtrMnda"
    t.integer  "IndExeDr"
    t.integer  "NroLinRef"
    t.string   "TpoDocRef"
    t.integer  "IndGlobal"
    t.string   "FolioRef"
    t.date     "FchRef"
    t.integer  "CodRef"
    t.string   "RazonRef"
    t.text     "X509Certificate"
    t.string   "SignatureValue"
    t.date     "Tmstfirma"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pruebas", force: true do |t|
    t.string   "rut"
    t.string   "nombre"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", force: true do |t|
    t.string   "email"
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.string   "nombres"
    t.string   "apellidos"
    t.string   "fono"
    t.string   "password"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true

end
