# Tipos de documentos
Tipodte.find_or_create_by_tipo(tipo: 30, nombre: "Factura", manual: "S")
Tipodte.find_or_create_by_tipo(tipo: 32, manual: "S", nombre: "Factura exenta") 
Tipodte.find_or_create_by_tipo(tipo: 35, manual: "S",nombre: "Boleta")
Tipodte.find_or_create_by_tipo(tipo: 38, manual: "S",nombre: "Boleta exenta")
Tipodte.find_or_create_by_tipo(tipo: 45, manual: "S",nombre: "Factura de compra")
Tipodte.find_or_create_by_tipo(tipo: 55, manual: "S",nombre: "N/D")
Tipodte.find_or_create_by_tipo(tipo: 60, manual: "S",nombre: "N/C")
Tipodte.find_or_create_by_tipo(tipo: 103, manual: "S",nombre: "Liquidacion")
Tipodte.find_or_create_by_tipo(tipo: 40, manual: "S",nombre: "Liquidacion Factura")
Tipodte.find_or_create_by_tipo(tipo: 43, manual: "N",nombre: "Liquidacion-Factura Electr.")
Tipodte.find_or_create_by_tipo(tipo: 33, manual: "N",nombre: "Factura Electr.")
Tipodte.find_or_create_by_tipo(tipo: 34, manual: "N",nombre: "Factura Exenta Electr.")
Tipodte.find_or_create_by_tipo(tipo: 39, manual: "N",nombre: "Boleta Electr.")
Tipodte.find_or_create_by_tipo(tipo: 41, manual: "N",nombre: "Boleta Exenta Electr.")
Tipodte.find_or_create_by_tipo(tipo: 46, manual: "N",nombre: "Factura de Compra Electr.")
Tipodte.find_or_create_by_tipo(tipo: 56, manual: "N",nombre: "Nota de Debito Electr.")
Tipodte.find_or_create_by_tipo(tipo: 61, manual: "N",nombre: "Nota de Credito Electr.")
Tipodte.find_or_create_by_tipo(tipo: 50, manual: "S",nombre: "Guia de Despacho")
Tipodte.find_or_create_by_tipo(tipo: 52, manual: "N",nombre: "Guia de Despacho Electr.")
Tipodte.find_or_create_by_tipo(tipo: 110, manual: "N",nombre: "Factura de Exportacion Electr.")
Tipodte.find_or_create_by_tipo(tipo: 111, manual: "N",nombre: "N/D Exportacion Electr.")
Tipodte.find_or_create_by_tipo(tipo: 112, manual: "N",nombre: "N/C Exportacion Electr.")
Tipodte.find_or_create_by_tipo(tipo: 801, manual: "S",nombre: "O/C")
Tipodte.find_or_create_by_tipo(tipo: 802, manual: "S",nombre: "Nota de pedido")
Tipodte.find_or_create_by_tipo(tipo: 803, manual: "S",nombre: "Contrato")
Tipodte.find_or_create_by_tipo(tipo: 804, manual: "S",nombre: "Resolucion")
Tipodte.find_or_create_by_tipo(tipo: 805, manual: "S",nombre: "Proceso ChileCompra")
Tipodte.find_or_create_by_tipo(tipo: 806, manual: "S",nombre: "Ficha ChileCompra")
Tipodte.find_or_create_by_tipo(tipo: 807, manual: "S",nombre: "DUS")
Tipodte.find_or_create_by_tipo(tipo: 808, manual: "S",nombre: "B/L (Conocimiento de embarque)")
Tipodte.find_or_create_by_tipo(tipo: 809, manual: "S",nombre: "AWB (Air Will Bill)")
Tipodte.find_or_create_by_tipo(tipo: 810, manual: "S",nombre: "MIC/DTA")
Tipodte.find_or_create_by_tipo(tipo: 811, manual: "S",nombre: "Carta de Porte")
Tipodte.find_or_create_by_tipo(tipo: 812, manual: "S",nombre: "Resolucion del SNA donde califica Servicios de Exportacion")
Tipodte.find_or_create_by_tipo(tipo: 813, manual: "S",nombre: "Pasaporte")
Tipodte.find_or_create_by_tipo(tipo: 814, manual: "S",nombre: "Certificado de Deposito Bolsa Prod. Chile.")
Tipodte.find_or_create_by_tipo(tipo: 815, manual: "S",nombre: "Vale de Prenda Bolsa Prod. Chile")


User.find_or_create_by_email(email: "admin@invoicedigital.cl" , password: "invoice1234", password_confirmation: "invoice1234")
Admin.find_or_create_by_email(email: "admin@invoicedigital.cl" )

