#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.pop3 = {
  server: 'mail.lubba.cl', port: 995, ssl: true,
  username: 'notificaciones@lubba.cl',
  password: 'lubba10580'
 }


Mailman::Application.run do
  default do
    begin
      puts "Received: #{message.subject}" 
      puts "Received: #{message.body}" 
      puts  "attachment: #{message.attachment}"


    rescue
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end  
end
