class CreateCreditnotes < ActiveRecord::Migration
  def change
    create_table :creditnotes do |t|
      t.string :Version
      t.integer :TipoDTE
      t.integer :Folio
      t.date :FchEmis
      t.integer :IndNoRebaja
      t.integer :IndServicio
      t.integer :MntBruto
      t.integer :FmaPago
      t.string :FchCancel
      t.integer :MntCancel
      t.integer :SaldoInsol
      t.date :FchPago
      t.integer :MntPago
      t.string :GlosaPagos
      t.date :PeriodoDesde
      t.date :PeriodoHasta
      t.string :MedioPago
      t.string :TipoCtaPago
      t.string :NumCtaPago
      t.string :BcoPago
      t.string :TermPagoCdg
      t.string :TermPagoGlosa
      t.integer :TermPagoDias
      t.date :FchVenc
      t.string :RUTEmisor
      t.string :RznSoc
      t.string :GiroEmis
      t.string :Telefono
      t.string :CorreoEmisor
      t.integer :Acteco
      t.string :Sucursal
      t.integer :CdgSIISucur
      t.string :DirOrigen
      t.string :CmnaOrigen
      t.string :CiudadOrigen
      t.string :CdgVendedor
      t.string :RUTMandante
      t.string :RUTRecep
      t.string :CdgIntRecep
      t.string :RznSocRecep
      t.string :NumId
      t.string :Nacionalidad
      t.string :GiroRecep
      t.string :Contacto
      t.string :CorreoRecep
      t.string :DirRecep
      t.string :CmnaRecep
      t.string :CiudadRecep
      t.string :DirPostal
      t.string :CmnaPostal
      t.string :CiudadPostal
      t.string :RUTSolicita
      t.string :RUTChofer
      t.string :NombreChofer
      t.string :DirDest
      t.string :CmnaDest
      t.string :CiudadDest
      t.integer :MntNeto
      t.integer :MntExe
      t.integer :MntBase
      t.integer :MntMargenCom
      t.integer :TasaIVA
      t.integer :IVA
      t.integer :IVAProp
      t.integer :IVATerc
      t.string :TipoImp
      t.integer :TasaImp
      t.integer :MontoImp
      t.integer :IVANoRet
      t.integer :CredEC
      t.integer :GrntDep
      t.integer :ValComNeto
      t.integer :ValComExe
      t.integer :ValComIVA
      t.integer :MntTotal
      t.integer :MontoNF
      t.integer :MontoPeriodo
      t.integer :SaldoAnterior
      t.integer :VlrPagar
      t.string :TpoMoneda
      t.integer :TpoCambio
      t.integer :MntNetoOtrMnda
      t.integer :MntExeOtrMnda
      t.integer :MntFaeCarneOtrMnda
      t.integer :MntMargComOtrMnda
      t.integer :IVAOtrMnda
      t.string :TipoImpOtrMnda
      t.integer :TasaImpOtrMnda
      t.integer :VlrImpOtrMnda
      t.integer :IVANoRetOtrMnda
      t.integer :MntTotOtrMnda
      t.integer :NroSti
      t.text :GlosaSti
      t.integer :OrdenSti
      t.float :SubTotNetoSti
      t.float :SubTotIVASti
      t.float :SubTotAdicSti
      t.float :SubTotExeSti
      t.float :ValSubTotSti
      t.integer :LineasDeta
      t.integer :NroLinDr
      t.string :TpoMov
      t.string :GlosaDr
      t.string :TpoValor
      t.float :ValorDr
      t.float :ValorDrOtrMnda
      t.integer :IndExeDr
      t.integer :NroLinRef
      t.string :TpoDocRef
      t.integer :IndGlobal
      t.string :FolioRef
      t.string :RUTOtr
      t.date :FchRef
      t.integer :CodRef
      t.string :RazonRef
      t.integer :NroLinCom
      t.string :TipoMovim
      t.string :Glosa
      t.integer :TasaComision
      t.integer :ValComNeto
      t.integer :ValComExe
      t.integer :ValComIVA
      t.text :X509Certificate
      t.string :SignatureValue
      t.date :Tmstfirma

      t.timestamps
    end
  end
end
