class CreateInvoices < ActiveRecord::Migration
  def change
    create_table :invoices do |t|
      t.string :Version
      t.integer :TipoDte
      t.integer :Folio
      t.date :FchEmis
      t.string :TipoDespacho
      t.integer :IndServicio
      t.integer :MntBruto
      t.integer :FmaPago
      t.date :FchCancel
      t.integer :MntCancel
      t.integer :SaldoInsol
      t.date :FchPago
      t.integer :MntPago
      t.string :GlosaPagos
      t.date :PeriodoDesde
      t.date :PeriodoHasta
      t.string :MedioPago
      t.string :TipoCtaPAgo
      t.string :NumCtaPago
      t.string :BcoPago
      t.string :TermPagoCdg
      t.string :TermPAgoGlosa
      t.integer :TermPagoDias
      t.date :FchVenc
      t.string :RUTEmisor
      t.string :RznSoc
      t.string :GiroEmis
      t.string :Telefono
      t.string :CorreoEmisor
      t.integer :Acteco
      t.string :Sucursal
      t.integer :CdgSIISucur
      t.string :DirOrigen
      t.string :CmnaOrigen
      t.string :CiudadOrigen
      t.string :CdgVendedor
      t.string :RutMandante
      t.string :RUTReceptor
      t.string :CdgIntRecep
      t.string :RznSocRecep
      t.string :NumId
      t.string :Nacionalidad
      t.string :GiroRecep
      t.string :Contacto
      t.string :CorreoRecep
      t.string :DirRecep
      t.string :CmnaRecep
      t.string :CiudadRecep
      t.string :DirPostal
      t.string :CmnaPostal
      t.string :CiudadPostal
      t.string :RUTSolicita
      t.string :Patente
      t.string :RUTTRans
      t.string :RUTChofer
      t.string :NombreChofer
      t.string :DirDest
      t.string :CmnaDest
      t.string :CiudadDest
      t.integer :MntNeto
      t.integer :MntExe
      t.integer :MntBase
      t.integer :MntMargenCom
      t.float :TasaIVA
      t.integer :IVA
      t.integer :IVAProp
      t.integer :IVATerc
      t.string :TipoImp
      t.integer :TasaImp
      t.integer :MontoImp
      t.integer :CredEC
      t.integer :GmtDep
      t.integer :MntTotal
      t.integer :MontoNF
      t.integer :MontoPeriodo
      t.integer :SaldoAnterior
      t.integer :VlrPagar
      t.string :TpoMoneda
      t.integer :TpoCambio
      t.float :MntNetoOtrMnda
      t.float :MntExeOtrMnda
      t.float :MntFaeCarneOtrMnda
      t.integer :MntMargComOtrMnda
      t.float :IVAOtrMnda
      t.string :TipoImpOtrMnda
      t.integer :TasaImpOtrMnda
      t.integer :VlrImpOtrMnda
      t.float :MntTotOtrMnda
      t.string :NroSti
      t.string :integer
      t.string :GlosaSti
      t.string :text
      t.string :OrdenSti
      t.string :integer
      t.string :SubTotNetoSti
      t.string :float
      t.string :SubTotIVASti
      t.string :float
      t.string :SubTotAdicSti
      t.string :float
      t.string :SubTotExeSti
      t.string :float
      t.string :ValSubTotSti
      t.string :float
      t.string :LineasDeta
      t.string :integer
      t.integer :NroLinDr
      t.string :TpoMov
      t.string :GlosaDr
      t.string :TpoValor
      t.float :ValorDr
      t.float :ValorDrOtrMnda
      t.integer :IndExeDr
      t.integer :NroLinRef
      t.string :TpoDocRef
      t.integer :IndGlobal
      t.string :FolioRef
      t.date :FchRef
      t.integer :CodRef
      t.string :RazonRef
      t.text :X509Certificate
      t.string :SignatureValue
      t.date :Tmstfirma

      t.timestamps
    end
  end
end
