class CreateDocumentos < ActiveRecord::Migration
  def change
    create_table :documentos do |t|
      t.string :TipoDTE
      t.string :integer
      t.string :Folio
      t.string :integer
      t.string :FchEmis
      t.string :string
      t.string :IndNoRebaja
      t.string :integer
      t.string :TipoDespacho
      t.string :integer
      t.string :IndTraslado
      t.string :integer
      t.string :TpoImpresion
      t.string :string
      t.string :IndServicio
      t.string :integer
      t.string :MntBruto
      t.string :integer
      t.string :FmaPago
      t.string :integer
      t.string :FchVenc
      t.string :string
      t.string :RUTEmisor
      t.string :string
      t.string :RznSoc
      t.string :string
      t.string :GiroEmis
      t.string :string
      t.string :Telefono
      t.string :string
      t.string :CorreoEmisor
      t.string :string
      t.string :Acteco
      t.string :integer
      t.string :CdgTraslado
      t.string :integer
      t.string :FolioAut
      t.string :integer
      t.string :FchAut
      t.string :string
      t.string :Sucursal
      t.string :string
      t.string :CdgSIISucur
      t.string :integer
      t.string :CodAdicSucur
      t.string :string
      t.string :DirOrigen
      t.string :string
      t.string :CmnaOrigen
      t.string :string
      t.string :CiudadOrigen
      t.string :string
      t.string :CdgVendedor
      t.string :integer
      t.string :IdAdicEmisor
      t.string :string
      t.string :RUTMandante
      t.string :string
      t.string :RUTRecep
      t.string :string
      t.string :CdgIntRecep
      t.string :string
      t.string :RznSocRecep
      t.string :string
      t.string :NumId
      t.string :string
      t.string :Nacionalidad
      t.string :string
      t.string :IdAdicRecep
      t.string :string
      t.string :GiroRecep
      t.string :string
      t.string :Contacto
      t.string :string
      t.string :CorreoRecep
      t.string :string
      t.string :DirRecep
      t.string :string
      t.string :CmnaRecep
      t.string :string
      t.string :CiudadRecep
      t.string :string
      t.string :DirPostal
      t.string :string
      t.string :CmnaPostal
      t.string :string
      t.string :CiudadPostal
      t.string :string
      t.string :RUTSolicita
      t.string :string
      t.string :Patente
      t.string :string
      t.string :RUTTrans
      t.string :string
      t.string :RUTChofer
      t.string :string
      t.string :NombreChofer
      t.string :string
      t.string :DirDest
      t.string :string
      t.string :CmnaDest
      t.string :string
      t.string :CiudadDest
      t.string :string
      t.string :CodModVenta
      t.string :integer
      t.string :CodClauVenta
      t.string :integer
      t.string :TotClauVenta
      t.string :integer
      t.string :CodViaTransp
      t.string :integer
      t.string :NombreTransp
      t.string :string
      t.string :RUTCiaTransp
      t.string :string
      t.string :NomCiaTransp
      t.string :string
      t.string :IdAdicTransp
      t.string :string
      t.string :Booking
      t.string :string
      t.string :Operador
      t.string :string
      t.string :CodPtoEmbarque
      t.string :integer
      t.string :IdAdicPtoEmb
      t.string :string
      t.string :CodPtoDesemb
      t.string :string
      t.string :IdAdicPtoDesemb
      t.string :string
      t.string :Tara
      t.string :integer
      t.string :CodUnidMedTara
      t.string :integer
      t.string :PesoBruto
      t.string :integer
      t.string :CodUnidPesoBruto
      t.string :integer
      t.string :PesoNeto
      t.string :integer
      t.string :CodUnidPesoNeto
      t.string :integer
      t.string :TotItems
      t.string :integer
      t.string :TotBultos
      t.string :integer
      t.string :TpoMoneda
      t.string :string
      t.string :MntNeto
      t.string :integer
      t.string :MntExe
      t.string :integer
      t.string :MntBase
      t.string :integer
      t.string :MntMargenCom
      t.string :integer
      t.string :TasaIVA
      t.string :float
      t.string :IVA
      t.string :integer
      t.string :IVAProp
      t.string :integer
      t.string :IVATerc
      t.string :integer
      t.string :IVANoRet
      t.string :integer
      t.string :CredEC
      t.string :integer
      t.string :GrntDep
      t.string :integer
      t.string :ValComNeto
      t.string :integer
      t.string :ValComExe
      t.string :integer
      t.string :ValComIVA
      t.string :integer
      t.string :MntTotal
      t.string :integer
      t.string :MontoNF
      t.string :integer

      t.timestamps
    end
  end
end
